---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
     exclude_fingerprints:
    - f1aa7cb937ae65c16975340212ddbe79
    - e8b778522f85ba63a42a835a5cbf8b53
    - 236bd5b52b891f6b6d6c2aae71b67c42
    - ff169bcd7931f36bb8d533aae7ed155b
    - 5a5e3bf581040648d6e26fc1b57197f3
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- test/
- vendor/
