version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose: 
      - 5432
  web:
    build: .
    volumes:
      - .:/todorails
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      PGHOST: "db"
      PGUSER: "postgres"
      PGDBNAME: "todorails"
    depends_on:
      - db